# Generated by Django 5.1.5 on 2025-01-26 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("meta_origin", models.CharField(default="colvert", max_length=100)),
                ("meta_created_at", models.DateTimeField(auto_now_add=True)),
                ("meta_modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Scope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("meta_origin", models.CharField(default="colvert", max_length=100)),
                ("meta_created_at", models.DateTimeField(auto_now_add=True)),
                ("meta_modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Severity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("meta_origin", models.CharField(default="colvert", max_length=100)),
                ("meta_created_at", models.DateTimeField(auto_now_add=True)),
                ("meta_modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("meta_origin", models.CharField(default="colvert", max_length=100)),
                ("meta_created_at", models.DateTimeField(auto_now_add=True)),
                ("meta_modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UseCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uc_title", models.TextField()),
                ("uc_reference", models.CharField(max_length=100)),
                ("uc_description", models.TextField()),
                ("uc_comments", models.TextField()),
                ("uc_release_date", models.DateTimeField(blank=True, null=True)),
                (
                    "uc_Category_name",
                    models.CharField(
                        default="Not Defined", editable=False, max_length=100
                    ),
                ),
                (
                    "uc_Scope_name",
                    models.CharField(
                        default="Not Defined", editable=False, max_length=100
                    ),
                ),
                (
                    "uc_Severity_name",
                    models.CharField(
                        default="Not Defined", editable=False, max_length=20
                    ),
                ),
                ("uc_247_possible", models.BooleanField(default=False)),
                ("uc_247_activated", models.BooleanField(default=False)),
                ("uc_origin_status", models.CharField(max_length=100, null=True)),
                (
                    "local_Status_name",
                    models.CharField(
                        default="Not Defined", editable=False, max_length=50
                    ),
                ),
                ("uc_triggered_occurances", models.IntegerField(default=0)),
                ("uc_last_triggered_at", models.DateField(blank=True, null=True)),
                ("local_impl_expected_at", models.DateField(blank=True, null=True)),
                ("local_impl_major_priority", models.BooleanField(default=False)),
                ("local_doc_objective", models.TextField()),
                ("local_doc_requirements", models.TextField(blank=True, null=True)),
                ("local_doc_comments", models.TextField(blank=True, null=True)),
                ("local_doc_testing_method", models.TextField(blank=True, null=True)),
                ("local_doc_normal_situation", models.TextField(blank=True, null=True)),
                (
                    "local_doc_abnormal_situation",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "local_doc_detection_criteria",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "local_doc_alt_detection_criteria",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "local_doc_detection_limitations",
                    models.TextField(blank=True, null=True),
                ),
                ("local_doc_response", models.TextField(blank=True, null=True)),
                ("local_doc_queries", models.TextField(blank=True, null=True)),
                (
                    "meta_last_sync_origin",
                    models.CharField(default="colvert", max_length=100),
                ),
                ("meta_first_origin", models.CharField(editable=False, max_length=100)),
                ("meta_created_at", models.DateTimeField(auto_now_add=True)),
                ("meta_modified_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_ucfields_metadata",
                    models.JSONField(default=dict, editable=False),
                ),
                (
                    "local_Status_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usecases",
                        to="core.status",
                    ),
                ),
                (
                    "uc_Category_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usecases",
                        to="core.category",
                    ),
                ),
                (
                    "uc_Scope_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usecases",
                        to="core.scope",
                    ),
                ),
                (
                    "uc_Severity_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usecases",
                        to="core.severity",
                    ),
                ),
            ],
        ),
    ]
